name: hw3_env

channels:
- conda-forge
dependencies:
- conda-forge::python=2.7
- conda-forge::scikit-learn
- conda-forge::pandas
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::gxx_linux-64
- conda-forge::libiconv=1.15