"""In this question you will be filtering for patients that have positive response to treatment

You'll implement a function to make each section of main() work.
Each function should only require a few lines of code, so if you have more than 5
you may be overthinking it
"""
import os
import pandas as pd

from tests import test_q1_shape


def create_dataframe(path_to_datafile):
    """Create a dataframe from the data stored at the given path
    Inputs
    ------
    path_to_datafile: str
         The path to the datafile
         
    Returns
    -------
    df: pandas.DataFrame
        The dataframe representation of the data
        
    """
    df = # Your code here

    return df


def filter_patients(df):
    """Filter the data to contain only those patients that have
    a positive effect
    
    Input
    -----
    df: pandas.DataFrame
        The dataframe generated by read_data
        
    Returns
    -------
    nonzero_df: pandas.DataFrame
        The dataframe after filtering
    
    """
    nonzero_df = # Your code here
    return nonzero_df


def main():
    # Find the path to the data
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(current_dir, "data/patient_responses.csv")

    # 1. Read in data
    df = create_dataframe(data_path)

    # 2. Filter data for positive effect
    nonzero_df = filter_patients(df)
    test_q1_shape(nonzero_df)

    return nonzero_df


if __name__ == "__main__":
    main()
