"""In this problem you will be creating box plots from the data in box_plot.tsv

You'll implement a function to make each section of main() work.
Each function should only require a few lines of code, so if you have more than 5
you may be overthinking it
"""

import os

import pandas as pd
from plotnine import ggplot, aes, geom_violin, geom_boxplot

from test import test_box_read, test_box_melt

def read_data(data_path):
    """Read the data at the given path into a dataframe.
    Note that this time the data is stored in a tab separated file instead of a comma separated one

    Input
    -----
    data_path: str
        The path to the dataset

    Returns
    -------
    box_df: pandas.DataFrame
        The dataframe read in from the file
    """
    box_df = pd.read_csv(data_path, sep='\t')
    return box_df


def melt_data(box_df):
    """Reformat the data to contain two columns: one denoting whether the patient was treated
    or used as a control and the other measuring the patient's blood pressure

    Input
    -----
    box_df: pandas.DataFrame
        The dataframe generated by read_data

    Returns
    -------
    box_df: pandas.DataFrame
        The dataframe after reformatting
    """
    box_df = box_df.melt()
    box_df = box_df.rename(columns={'variable': 'treated/control', 'value': 'blood_pressure'})

    return box_df


def create_boxplot(box_df):
    """This function should create a boxplot from the dataframe created in melt_data

    Input
    -----
    box_df: pandas.DataFrame
        The dataframe returned by melt_data

    Returns
    -------
    plot: plotnine.ggplot
        A boxplot visualizing the data in box_df
    """
    plot = ggplot(box_df, aes(x='treated/control', y='blood_pressure', fill='treated/control')) + geom_boxplot()

    return plot


def create_violin_plot(box_df):
    """This function should create a violin plot from the dataframe created in melt_data

    Input
    -----
    box_df: pandas.DataFrame
        The dataframe returned by melt_data

    Returns
    -------
    plot: plotnine.ggplot
        A violin plot visualizing the data in box_df
    """
    plot = ggplot(box_df, aes(x='treated/control', y='blood_pressure', fill='treated/control')) + geom_violin()

    return plot


def main():
    # Find the path to the data
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(current_dir, 'data/box_plot.tsv')

    # 1. Read in data
    box_df = read_data(data_path)
    test_box_read(box_df)

    # 2. Reformat the data for use in plots
    box_df = melt_data(box_df)
    test_box_melt(box_df)

    # 3. Create a box plot
    print(create_boxplot(box_df))

    # 4. Create a violin plot
    print(create_violin_plot(box_df))

    print('What is the difference between the box plot and the violin plot?')
    print("What does your violin plot tell you that the box plot doesn't?")


if __name__ == '__main__':
    main()
